services:
  postgres-user :
    image: postgres:14.22-trixie
    environment:
      POSTGRES_DB: smartshop_users
      POSTGRES_USER: smartshop
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres-product:
    image: postgres:14.22-trixie
    environment:
      POSTGRES_DB: smartshop_products
      POSTGRES_USER: smartshop
      POSTGRES_PASSWORD: secret

    ports:
      - "5433:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data

  redis:
    image: redis:8.8-m03-trixie
    ports:
      - "6379:6379"

  kafka:
    image: apache/kafka:4.3.1-rc1
    container_name: mykafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,EXTERNAL://mykafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@mykafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  kafka-ui:
    image: kafbat/kafka-ui:aa21129
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: mykafka:29092

  mongo:
    image: arm64v8/mongo:8-noble
    container_name: mongodb
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: smartshop_read
      MONGO_INITDB_ROOT_USERNAME: smartshop
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
        - mongo_data:/data/db

volumes:
    postgres_user_data:
    postgres_product_data:
    mongo_data: