server:
  port: 8070

spring:
  application:
    name: api-gateway
  cloud:
    gateway.server.webflux.routes:
        # Auth routes — NO JWT required
        - id: user-service-auth
          uri: lb://USER-SERVICE       # lb:// = load-balanced via Eureka
          predicates:
            - Path=/api/auth/**

        # Protected user routes — JWT required
        - id: user-service-protected
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - JwtAuthentication             # your custom JWT filter

      # Protected user routes — JWT required
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
            - Method=POST,PUT,DELETE,PATCH
          filters:
             - name: JwtAuthentication
               args:
                 roles: SELLER,ADMIN             # your custom JWT filter

        - id: product-service-get-product
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
            - Method=GET

        - id: product-service-category
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/category/**
            - Method=POST
          filters:
            - name: JwtAuthentication
              args:
                roles: SELLER,ADMIN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: ${JWT_SECRET}
